version: '2'
services:
  web:
    image: odoo:8.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./data/addons:/mnt/extra-addons
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
      - ./data/db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
